# Generated by Django 3.2.3 on 2021-05-27 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('form_id', models.IntegerField(primary_key=True, serialize=False)),
                ('form_object', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationRubricTemplate',
            fields=[
                ('rubric_template_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('object', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStage',
            fields=[
                ('stage_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStageTemplate',
            fields=[
                ('stage_template_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('object', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RubricItem',
            fields=[
                ('rubric_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.IntegerField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_recruitment.department')),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('job_opening', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_panel', models.JSONField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_recruitment.applicationform')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_recruitment.position')),
                ('rubric_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_recruitment.applicationrubrictemplate')),
                ('stage_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_recruitment.applicationstagetemplate')),
            ],
        ),
    ]
