# Generated by Django 3.2.3 on 2021-05-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobopening',
            old_name='form_id',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='jobopening',
            old_name='job_opening_id',
            new_name='job_opening',
        ),
        migrations.RenameField(
            model_name='jobopening',
            old_name='position_id',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='jobopening',
            old_name='rubric_template_id',
            new_name='rubric_template',
        ),
        migrations.RenameField(
            model_name='jobopening',
            old_name='stage_template_id',
            new_name='stage_template',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='department_id',
            new_name='department',
        ),
    ]
